# Numpy 1
# Array Creation
## 1. Array Creation with list

In [20]:
import numpy as np

list = [1, 2, 3, 4]
arr1 = np.array(list) 		#1d
print(arr1)
print(list)

[1 2 3 4]
[1, 2, 3, 4]


## 2. Create Array with Tuple

In [21]:
tuple = (1, 2, 3, 4)
arr2 = np.array(tuple)
print("Array: ", arr2)
print("Tuple: ", tuple)

Array:  [1 2 3 4]
Tuple:  (1, 2, 3, 4)


# Checking the type of array

In [22]:
print(type(arr1))

<class 'numpy.ndarray'>


# n-Dimensional Array

In [23]:
arr3 = np.array([1, 2, 3, 4])														#1d array
arr4 = np.array([[1, 2], [3, 4]])													#2d array
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])				#3d array

print(arr3)
print()

print(arr4)
print()

print(arr5)
print()

[1 2 3 4]

[[1 2]
 [3 4]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]



# Array Attributes
## 1. ndim
Number of array dimensions.

In [24]:
print(arr3.ndim)
print(arr4.ndim)

# y = np.zeros((2, 3, 4), dtype=int)
# y.ndim
# print(y)

1
2


## 2. shape
Return the shape of an array.

In [25]:
print(arr3.shape)
print(arr4.shape)

(4,)
(2, 2)


## 3. size
Number of elements in the array.

In [26]:
print(arr3.size)
print(arr4.size)

4
4


## 4. dtype
Returns out datatype of the array

In [27]:
print(arr3.dtype)
print(arr4.dtype)

int64
int64


# Array with mixed data type

In [28]:
arr6 = [1, 2, 3.5, 'V', "virat Kohli"]
arr7 = [1, 5, 3.6]
arr8 = np.array(arr6)
arr9 = np.array(arr7)
print(arr8, arr9)

['1' '2' '3.5' 'V' 'virat Kohli'] [1.  5.  3.6]


# Built in Array Creation
## 1. ones()

In [29]:
print(np.ones(18))
print(np.ones((5, 6)))


    

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


## 2. zeros

In [30]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


## 3. arange(start, stop, step)

In [31]:
print(np.arange(1, 10, 2))

[1 3 5 7 9]


## 4. linspace(start, stop, num=50)
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)


In [32]:
print(np.linspace(1, 10, 3))

[ 1.   5.5 10. ]
