In [ ]:
#
import numpy as np

arr1d = np.array([1,2,3,4])
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# 1. Indexing
## 1D idexing



In [ ]:
arr1d[1]
arr1d[-2]

arr1d[1:]
arr1d[1:3:1]
arr1d[::2]

array([1, 3])

## 2D indexing

In [ ]:
#array[row_index, col_index]

# print(arr2d[0][1])
# print(arr2d[(0, 1)])
arr2d[:,1]

#slicing
#array[row:row, col:col]
arr2d[:2,1:]
arr2d[:,1:2]
arr2d[1:, :2]

array([[4, 5],
       [7, 8]])

## 3d indexing

In [ ]:
#array[block, row, column]
arr3d[0,0,1]
arr3d[1,0,1]
arr3d[1][0][1]


#slicing
arr3d[:, :, 1]

array([[ 2,  5],
       [ 8, 11]])

#Boolean Indexing
1.it eliminats the need foer loops
2.it provides data filtering which is essential for data anaylysis.


In [ ]:
arr1d=np.array([1,2,3,4])
print(arr1d[arr < 3])


NameError: name 'arr' is not defined

In [ ]:
list=np.array(["apple","mango","orange","apple","apple"])
print([list == 'apple'])
print(list[list == 'apple'])

[array([ True, False, False,  True,  True])]
['apple' 'apple' 'apple']


In [ ]:
list=np.array([10,20,3o,40,50,60])
print([list >= 20] and [list <= 40])
print(list[list == 'apple'])

In [ ]:
arr = np.array([-1, -3, -4, 10, 20 ,30])
print(arr[arr >= 0])
print(arr[arr < 0])

[10 20 30]
[-1 -3 -4]
