# element-wise operation
the operation is applied to each corresponding element of the array. no loops are required

In [ ]:
import numpy as np
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])

print(a+b)


arr2 = np.array([[1, 2, 3], [2, 3, 4]])
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2+arr3)

[ 7  9 11]
[[ 2  4  6]
 [ 6  8 10]]


# array scalar operation
scalar is applied to each elements.

In [ ]:
print(a * 5)

[10 15 20]


# matrix multiplication


In [ ]:
mat1 = np.array([[2, 3], [5, 6]])
mat2 = np.array([[4, 5], [1, 2]])

print(mat1 * mat2)
print(mat1 @ mat2) # matrix multiplicaiton


[[ 8 15]
 [ 5 12]]
[[11 16]
 [26 37]]


# universal function(unfuncs)
it is a vectorised function that perform element wise operation on array.


In [ ]:
np.add(a, b)
np.subtract(a, b)

array([-3, -3, -3])

# Broadcasting
it is a mechanism that allows arrays of different shapes to be used together in arthimetic operation, instead of manually reshaping the array, numpy automatically broadcasts the smaller array accros the larger one to make thier shape compatible

## rules for broadcasting
- compare shaped form right to left
- 2d are compatible if they are equal or one of them is 1d.
- expand dimension if one array has fewer dimension than the other, prepend one to it's shape, until the no. of dimension matches

In [ ]:
arr1 = np.array([[1, 2, 3], [2, 3, 4]])
arr2 = np.array([1, 2, 3])

print()

# Aggrigation funciton
It process an entire array to return a single summary value.

## Common functions are
1. sum()
2. mean()
3. min()
4. max()
5. std(): standard deviation
6. var(): variance
7. prod(): product

In [ ]:
arr1 = np.array([2, 4, 7])

#sum
print(np.sum(arr1))

#mean
print(np.mean(arr1))

#min
print(np.min(arr1))

#max
print(np.max(arr1))

#std
print(np.std(arr1))

#var
print(np.var(arr1))

#prod
print(np.prod(arr1))

13
4.333333333333333
2
7
2.0548046676563256
4.222222222222222
56
